# Generated by Django 3.0.3 on 2020-02-29 22:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Describe current quest')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author_rating', models.IntegerField(help_text='Rating of user based on quests he authored', validators=[django.core.validators.MinValueValidator(0)])),
                ('player_rating', models.IntegerField(help_text='Rating of user based on quests he played', validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Quests')),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=15)),
                ('type_of_answer', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('previous_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Stages')),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Quests')),
            ],
        ),
        migrations.AddField(
            model_name='quests',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Users'),
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False, help_text='Shows if session is currently running')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Users')),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Quests')),
            ],
            options={
                'unique_together': {('player_id', 'quest_id')},
            },
        ),
    ]
