# Generated by Django 3.0.3 on 2020-02-29 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='author_rating',
            field=models.IntegerField(default=0, help_text='Rating of user based on quests he authored', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='users',
            name='player_rating',
            field=models.IntegerField(default=0, help_text='Rating of user based on quests he played', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
